name: Basic Checkout Lab

# Trigger on push to main branch
on:
  push:
    branches:
      - main

# Define jobs and their steps
jobs:
  basic-checkout:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Step 2: List repository contents
      - name: bulid docker image
        run: docker build -t helloworld .

      - name: image run
        run: docker run --name hellocontainer helloworld
        
      
     
